project_id = "dizwufpchqmaxlbrfmnb"

[functions.admin-users]
verify_jwt = true

[functions.drive-storage]
verify_jwt = true

[functions.upload-to-drive]
verify_jwt = true

[functions.media-list]
verify_jwt = true

[functions.media-file]
verify_jwt = true
